import { WorkflowNode, NodeConnection, NodeCategory } from '../types/workflow';

export const INITIAL_NODES: WorkflowNode[] = [
  {
    id: 'node-1',
    type: 'trigger_push',
    title: 'Push Trigger',
    subtitle: 'Branch: main',
    category: 'Triggers',
    x: 100,
    y: 80,
    iconType: 'push',
    badge: 'TRIGGER',
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
    config: {
      branch: 'main',
    },
  },
  {
    id: 'node-2',
    type: 'repo_checkout',
    title: 'Checkout Repository',
    subtitle: 'actions/checkout@v4',
    category: 'Repository',
    x: 100,
    y: 240,
    iconType: 'checkout',
    badge: 'REPO',
    badgeColor: 'bg-neutral-800 text-yellow-300 border-neutral-700',
    config: {
      repository: 'self',
    },
  },
  {
    id: 'node-3',
    type: 'env_setup_node',
    title: 'Setup Node.js',
    subtitle: 'Version: 22',
    category: 'Environment',
    x: 100,
    y: 400,
    iconType: 'node',
    badge: 'ENV',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    config: {
      runtimeVersion: '22',
    },
  },
  {
    id: 'node-4',
    type: 'cmd_install',
    title: 'Install Dependencies',
    subtitle: 'npm ci',
    category: 'Commands',
    x: 100,
    y: 560,
    iconType: 'terminal',
    badge: 'CMD',
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
    config: {
      command: 'npm ci',
    },
  },
  {
    id: 'node-5',
    type: 'quality_test',
    title: 'Run Tests',
    subtitle: 'npm test',
    category: 'Quality',
    x: 100,
    y: 720,
    iconType: 'test',
    badge: 'TEST',
    badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
    config: {
      command: 'npm test',
    },
  },
  {
    id: 'node-6',
    type: 'quality_build',
    title: 'Build Project',
    subtitle: 'npm run build',
    category: 'Quality',
    x: 100,
    y: 880,
    iconType: 'build',
    badge: 'BUILD',
    badgeColor: 'bg-yellow-400/15 text-yellow-300 border-yellow-400/40',
    config: {
      command: 'npm run build',
    },
  },
  {
    id: 'node-7',
    type: 'deploy_ssh',
    title: 'Deploy via SSH',
    subtitle: 'docker compose up -d',
    category: 'Deployment',
    x: 100,
    y: 1040,
    iconType: 'deploy_ssh',
    badge: 'DEPLOY',
    badgeColor: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50',
    config: {
      sshHost: 'production.example.com',
      sshUser: 'deploy',
      sshPort: 22,
      command: 'docker compose up -d --build',
      secrets: {
        SSH_KEY: '${{ secrets.SSH_KEY }}',
      },
    },
  },
  {
    id: 'node-8',
    type: 'verify_health',
    title: 'HTTP Health Check',
    subtitle: 'Expected status: 200',
    category: 'Verification',
    x: 100,
    y: 1200,
    iconType: 'health',
    badge: 'VERIFY',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    config: {
      healthUrl: 'https://api.example.com/health',
      expectedStatus: 200,
    },
  },
];

export const INITIAL_CONNECTIONS: NodeConnection[] = [
  { id: 'conn-1', fromNodeId: 'node-1', toNodeId: 'node-2' },
  { id: 'conn-2', fromNodeId: 'node-2', toNodeId: 'node-3' },
  { id: 'conn-3', fromNodeId: 'node-3', toNodeId: 'node-4' },
  { id: 'conn-4', fromNodeId: 'node-4', toNodeId: 'node-5' },
  { id: 'conn-5', fromNodeId: 'node-5', toNodeId: 'node-6' },
  { id: 'conn-6', fromNodeId: 'node-6', toNodeId: 'node-7' },
  { id: 'conn-7', fromNodeId: 'node-7', toNodeId: 'node-8' },
];

export interface NodeTemplate {
  type: string;
  title: string;
  subtitle: string;
  category: NodeCategory;
  iconType: string;
  badge: string;
  badgeColor: string;
  defaultConfig: Record<string, any>;
}

export const NODE_CATALOG: Record<NodeCategory, NodeTemplate[]> = {
  Triggers: [
    {
      type: 'trigger_commit',
      title: 'Commit Event',
      subtitle: 'Trigger on commit to branch',
      category: 'Triggers',
      iconType: 'commit',
      badge: 'TRIGGER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { branch: 'main' },
    },
    {
      type: 'trigger_push',
      title: 'Push Event',
      subtitle: 'Trigger on push to branch',
      category: 'Triggers',
      iconType: 'push',
      badge: 'TRIGGER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { branch: 'main' },
    },
    {
      type: 'trigger_pr',
      title: 'Pull Request',
      subtitle: 'Trigger on PR opened/synced',
      category: 'Triggers',
      iconType: 'pr',
      badge: 'TRIGGER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { branch: 'main' },
    },
    {
      type: 'trigger_manual',
      title: 'Manual Dispatch',
      subtitle: 'workflow_dispatch',
      category: 'Triggers',
      iconType: 'manual',
      badge: 'TRIGGER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: {},
    },
    {
      type: 'trigger_cron',
      title: 'Schedule / Cron',
      subtitle: 'Recurring cron schedule',
      category: 'Triggers',
      iconType: 'cron',
      badge: 'TRIGGER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { cron: '0 0 * * *' },
    },
  ],
  Repository: [
    {
      type: 'repo_checkout',
      title: 'Checkout Repository',
      subtitle: 'actions/checkout@v4',
      category: 'Repository',
      iconType: 'checkout',
      badge: 'REPO',
      badgeColor: 'bg-neutral-800 text-yellow-300 border-neutral-700',
      defaultConfig: { repository: 'self', branch: 'main', fetchDepth: 1, submodules: false },
    },
    {
      type: 'repo_clone',
      title: 'Clone Repository',
      subtitle: 'git clone <url>',
      category: 'Repository',
      iconType: 'clone',
      badge: 'REPO',
      badgeColor: 'bg-neutral-800 text-yellow-300 border-neutral-700',
      defaultConfig: { repositoryUrl: 'https://github.com/org/repo.git', branch: 'main', targetPath: './external' },
    },
    {
      type: 'repo_fetch',
      title: 'Fetch Changes',
      subtitle: 'git fetch --all --tags',
      category: 'Repository',
      iconType: 'fetch',
      badge: 'REPO',
      badgeColor: 'bg-neutral-800 text-yellow-300 border-neutral-700',
      defaultConfig: { targetBranch: 'main', fetchTags: true, fetchDepth: 0 },
    },
    {
      type: 'repo_checkout_branch',
      title: 'Checkout Branch',
      subtitle: 'git checkout <branch>',
      category: 'Repository',
      iconType: 'checkout_branch',
      badge: 'BRANCH',
      badgeColor: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
      defaultConfig: { branchName: 'feature/ci-pipeline', createIfMissing: true, sourceBranch: 'main' },
    },
    {
      type: 'repo_checkout_commit',
      title: 'Checkout Commit',
      subtitle: 'git checkout <sha>',
      category: 'Repository',
      iconType: 'commit',
      badge: 'COMMIT',
      badgeColor: 'bg-yellow-500/10 text-yellow-300 border-yellow-500/30',
      defaultConfig: { commitSha: 'HEAD~1' },
    },
  ],
  Git: [
    {
      type: 'git_commit',
      title: 'Commit Changes',
      subtitle: 'git commit -m',
      category: 'Git',
      iconType: 'git_commit',
      badge: 'GIT',
      badgeColor: 'bg-amber-500/15 text-amber-300 border-amber-500/40',
      defaultConfig: { message: 'ci: update generated assets [skip ci]', authorName: 'github-actions[bot]', authorEmail: 'github-actions[bot]@users.noreply.github.com', files: '.' },
    },
    {
      type: 'git_push',
      title: 'Push Changes',
      subtitle: 'git push origin <branch>',
      category: 'Git',
      iconType: 'git_push',
      badge: 'GIT',
      badgeColor: 'bg-amber-500/15 text-amber-300 border-amber-500/40',
      defaultConfig: { branch: 'main', forcePush: false, pushTags: true },
    },
    {
      type: 'git_create_tag',
      title: 'Create Tag',
      subtitle: 'git tag -a <tag>',
      category: 'Git',
      iconType: 'git_tag',
      badge: 'TAG',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { tagName: 'v1.0.0', annotationMessage: 'Release v1.0.0', commitSha: 'HEAD' },
    },
    {
      type: 'git_merge',
      title: 'Merge Branch',
      subtitle: 'git merge <branch>',
      category: 'Git',
      iconType: 'git_merge',
      badge: 'MERGE',
      badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
      defaultConfig: { sourceBranch: 'staging', targetBranch: 'main', strategy: 'no-ff' },
    },
    {
      type: 'git_release',
      title: 'Create GitHub Release',
      subtitle: 'softprops/action-gh-release@v2',
      category: 'Git',
      iconType: 'git_release',
      badge: 'RELEASE',
      badgeColor: 'bg-yellow-400/20 text-yellow-300 border-yellow-400/40',
      defaultConfig: { tagName: 'v1.0.0', releaseName: 'Release v1.0.0', generateNotes: true, isDraft: false, isPrerelease: false },
    },
  ],
  Artifacts: [
    {
      type: 'artifact_upload',
      title: 'Upload Artifact',
      subtitle: 'actions/upload-artifact@v4',
      category: 'Artifacts',
      iconType: 'artifact_upload',
      badge: 'ARTIFACT',
      badgeColor: 'bg-yellow-400/10 text-yellow-400 border-yellow-400/30',
      defaultConfig: { artifactName: 'build-assets', artifactPath: './dist', retentionDays: 30, ifNoFilesFound: 'warn' },
    },
    {
      type: 'artifact_download',
      title: 'Download Artifact',
      subtitle: 'actions/download-artifact@v4',
      category: 'Artifacts',
      iconType: 'artifact_download',
      badge: 'ARTIFACT',
      badgeColor: 'bg-yellow-400/10 text-yellow-400 border-yellow-400/30',
      defaultConfig: { artifactName: 'build-assets', destinationPath: './dist' },
    },
    {
      type: 'artifact_build_output',
      title: 'Upload Build Output',
      subtitle: 'actions/upload-artifact@v4 (dist/)',
      category: 'Artifacts',
      iconType: 'artifact_build',
      badge: 'BUILD',
      badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
      defaultConfig: { artifactName: 'production-bundle', artifactPath: 'dist/', retentionDays: 14 },
    },
    {
      type: 'artifact_test_results',
      title: 'Upload Test Results',
      subtitle: 'actions/upload-artifact@v4 (reports/)',
      category: 'Artifacts',
      iconType: 'artifact_test',
      badge: 'TEST',
      badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      defaultConfig: { artifactName: 'junit-test-results', artifactPath: 'reports/**/*.xml', retentionDays: 14 },
    },
    {
      type: 'artifact_coverage',
      title: 'Upload Coverage Report',
      subtitle: 'actions/upload-artifact@v4 (coverage/)',
      category: 'Artifacts',
      iconType: 'artifact_coverage',
      badge: 'COVERAGE',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { artifactName: 'coverage-report', artifactPath: 'coverage/', retentionDays: 30 },
    },
    {
      type: 'artifact_logs',
      title: 'Upload Logs & Diagnostics',
      subtitle: 'actions/upload-artifact@v4 (*.log)',
      category: 'Artifacts',
      iconType: 'artifact_logs',
      badge: 'LOGS',
      badgeColor: 'bg-neutral-800 text-neutral-300 border-neutral-700',
      defaultConfig: { artifactName: 'runner-logs', artifactPath: '*.log', retentionDays: 7 },
    },
    {
      type: 'artifact_download_previous',
      title: 'Download Previous Build',
      subtitle: 'actions/download-artifact@v4',
      category: 'Artifacts',
      iconType: 'artifact_previous',
      badge: 'PREVIOUS',
      badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
      defaultConfig: { artifactName: 'production-bundle', destinationPath: './previous-build' },
    },
  ],
  Environment: [
    {
      type: 'env_setup_node',
      title: 'Setup Node.js',
      subtitle: 'actions/setup-node@v4',
      category: 'Environment',
      iconType: 'node',
      badge: 'ENV',
      badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      defaultConfig: { runtimeVersion: '22' },
    },
    {
      type: 'env_setup_python',
      title: 'Setup Python',
      subtitle: 'actions/setup-python@v5',
      category: 'Environment',
      iconType: 'python',
      badge: 'ENV',
      badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      defaultConfig: { runtimeVersion: '3.12' },
    },
    {
      type: 'env_setup_go',
      title: 'Setup Go',
      subtitle: 'actions/setup-go@v5',
      category: 'Environment',
      iconType: 'go',
      badge: 'ENV',
      badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      defaultConfig: { runtimeVersion: '1.23' },
    },
    {
      type: 'env_setup_docker',
      title: 'Setup Docker Buildx',
      subtitle: 'docker/setup-buildx-action@v3',
      category: 'Environment',
      iconType: 'setup_docker',
      badge: 'ENV',
      badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
      defaultConfig: {},
    },
  ],
  Commands: [
    {
      type: 'cmd_run',
      title: 'Run Shell Command',
      subtitle: 'Custom bash command',
      category: 'Commands',
      iconType: 'terminal',
      badge: 'CMD',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { command: 'echo "Executing command"' },
    },
    {
      type: 'cmd_script',
      title: 'Run Script File',
      subtitle: 'Execute ./scripts/deploy.sh',
      category: 'Commands',
      iconType: 'script',
      badge: 'CMD',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { command: 'bash ./scripts/deploy.sh' },
    },
  ],
  Quality: [
    {
      type: 'quality_test',
      title: 'Run Tests',
      subtitle: 'npm test / pytest',
      category: 'Quality',
      iconType: 'test',
      badge: 'TEST',
      badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
      defaultConfig: { command: 'npm test' },
    },
    {
      type: 'quality_lint',
      title: 'Run Linter',
      subtitle: 'npm run lint',
      category: 'Quality',
      iconType: 'lint',
      badge: 'LINT',
      badgeColor: 'bg-amber-400/10 text-amber-300 border-amber-400/30',
      defaultConfig: { command: 'npm run lint' },
    },
    {
      type: 'quality_build',
      title: 'Build Project',
      subtitle: 'npm run build',
      category: 'Quality',
      iconType: 'build',
      badge: 'BUILD',
      badgeColor: 'bg-yellow-400/15 text-yellow-300 border-yellow-400/40',
      defaultConfig: { command: 'npm run build' },
    },
  ],
  Docker: [
    {
      type: 'docker_login',
      title: 'Docker Login',
      subtitle: 'docker/login-action@v3',
      category: 'Docker',
      iconType: 'docker_login',
      badge: 'DOCKER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { registry: 'docker.io', username: '${{ secrets.DOCKER_USERNAME }}' },
    },
    {
      type: 'docker_build',
      title: 'Build Image',
      subtitle: 'docker build -t app:tag',
      category: 'Docker',
      iconType: 'docker_build',
      badge: 'DOCKER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { dockerImage: 'myapp', dockerTag: 'latest' },
    },
    {
      type: 'docker_push',
      title: 'Push Image',
      subtitle: 'docker push app:tag',
      category: 'Docker',
      iconType: 'docker_push',
      badge: 'DOCKER',
      badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
      defaultConfig: { dockerImage: 'myapp', dockerTag: 'latest' },
    },
  ],
  Deployment: [
    {
      type: 'deploy_ssh',
      title: 'Deploy via SSH',
      subtitle: 'Execute remote SSH command',
      category: 'Deployment',
      iconType: 'deploy_ssh',
      badge: 'DEPLOY',
      badgeColor: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50',
      defaultConfig: { sshHost: 'production.example.com', sshUser: 'deploy', sshPort: 22, command: 'docker compose up -d' },
    },
    {
      type: 'deploy_rsync',
      title: 'Deploy via Rsync',
      subtitle: 'Sync build artifacts to host',
      category: 'Deployment',
      iconType: 'deploy_rsync',
      badge: 'DEPLOY',
      badgeColor: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50',
      defaultConfig: { sshHost: 'production.example.com', sshUser: 'deploy', artifactPath: './dist' },
    },
  ],
  Logic: [
    {
      type: 'logic_if',
      title: 'Condition / IF',
      subtitle: "if: github.ref == 'refs/heads/main'",
      category: 'Logic',
      iconType: 'logic_if',
      badge: 'LOGIC',
      badgeColor: 'bg-amber-400/20 text-amber-300 border-amber-400/40',
      defaultConfig: { condition: "github.ref == 'refs/heads/main'" },
    },
  ],
  Verification: [
    {
      type: 'verify_health',
      title: 'HTTP Health Check',
      subtitle: 'Verify endpoint HTTP 200',
      category: 'Verification',
      iconType: 'health',
      badge: 'VERIFY',
      badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      defaultConfig: { healthUrl: 'https://api.example.com/health', expectedStatus: 200 },
    },
  ],
  Notifications: [
    {
      type: 'notify_slack',
      title: 'Slack Notification',
      subtitle: 'Post alert to Slack channel',
      category: 'Notifications',
      iconType: 'slack',
      badge: 'NOTIFY',
      badgeColor: 'bg-yellow-400/20 text-yellow-300 border-yellow-400/40',
      defaultConfig: { channel: '#deployments', webhookUrl: '${{ secrets.SLACK_WEBHOOK }}' },
    },
  ],
};
