import { WorkflowNode, NodeConnection } from '../types/workflow';

export function compileWorkflowToYaml(name: string, nodes: WorkflowNode[], connections: NodeConnection[]): string {
  // Sort nodes by connection order
  const nodeMap = new Map<string, WorkflowNode>();
  nodes.forEach(n => nodeMap.set(n.id, n));

  const incomingCount = new Map<string, number>();
  nodes.forEach(n => incomingCount.set(n.id, 0));
  connections.forEach(c => {
    incomingCount.set(c.toNodeId, (incomingCount.get(c.toNodeId) || 0) + 1);
  });

  const orderedNodes: WorkflowNode[] = [];
  const visited = new Set<string>();

  // Find root nodes (in-degree = 0)
  const queue: string[] = nodes.filter(n => incomingCount.get(n.id) === 0).map(n => n.id);

  while (queue.length > 0) {
    const currentId = queue.shift()!;
    if (visited.has(currentId)) continue;
    visited.add(currentId);

    const node = nodeMap.get(currentId);
    if (node) orderedNodes.push(node);

    // Find outgoing connections
    const outgoing = connections.filter(c => c.fromNodeId === currentId);
    for (const edge of outgoing) {
      const nextCount = (incomingCount.get(edge.toNodeId) || 1) - 1;
      incomingCount.set(edge.toNodeId, nextCount);
      if (nextCount <= 0 && !visited.has(edge.toNodeId)) {
        queue.push(edge.toNodeId);
      }
    }
  }

  // Include any remaining unvisited nodes
  nodes.forEach(n => {
    if (!visited.has(n.id)) orderedNodes.push(n);
  });

  // Extract triggers
  const triggerNodes = orderedNodes.filter(n => n.category === 'Triggers');
  const stepNodes = orderedNodes.filter(n => n.category !== 'Triggers');

  let yaml = `# Generated by noitca graphical workflow builder\nname: ${name || 'CI/CD Pipeline'}\n\non:\n`;

  if (triggerNodes.length === 0) {
    yaml += `  push:\n    branches:\n      - main\n  pull_request:\n    branches:\n      - main\n`;
  } else {
    triggerNodes.forEach(t => {
      if (t.type === 'trigger_push') {
        yaml += `  push:\n    branches:\n      - ${t.config.branch || 'main'}\n`;
      } else if (t.type === 'trigger_pr') {
        yaml += `  pull_request:\n    branches:\n      - ${t.config.branch || 'main'}\n`;
      } else if (t.type === 'trigger_manual') {
        yaml += `  workflow_dispatch:\n`;
      } else if (t.type === 'trigger_cron') {
        yaml += `  schedule:\n    - cron: '${t.config.cron || '0 0 * * *'}'\n`;
      }
    });
  }

  yaml += `\njobs:\n  deploy:\n    name: Build & Deploy\n    runs-on: ubuntu-latest\n\n    steps:\n`;

  if (stepNodes.length === 0) {
    yaml += `      - name: Checkout repository\n        uses: actions/checkout@v4\n`;
  } else {
    stepNodes.forEach(step => {
      yaml += `      - name: "${step.title}"\n`;

      if (step.config.condition) {
        yaml += `        if: ${step.config.condition}\n`;
      }

      switch (step.type) {
        case 'repo_checkout':
          yaml += `        uses: actions/checkout@v4\n`;
          break;
        case 'env_setup_node':
          yaml += `        uses: actions/setup-node@v4\n        with:\n          node-version: '${step.config.runtimeVersion || '22'}'\n`;
          break;
        case 'env_setup_python':
          yaml += `        uses: actions/setup-python@v5\n        with:\n          python-version: '${step.config.runtimeVersion || '3.12'}'\n`;
          break;
        case 'env_setup_go':
          yaml += `        uses: actions/setup-go@v5\n        with:\n          go-version: '${step.config.runtimeVersion || '1.23'}'\n`;
          break;
        case 'env_setup_docker':
          yaml += `        uses: docker/setup-buildx-action@v3\n`;
          break;
        case 'repo_upload_artifact':
          yaml += `        uses: actions/upload-artifact@v4\n        with:\n          name: ${step.config.artifactName || 'dist'}\n          path: ${step.config.artifactPath || './dist'}\n`;
          break;
        case 'repo_download_artifact':
          yaml += `        uses: actions/download-artifact@v4\n        with:\n          name: ${step.config.artifactName || 'dist'}\n`;
          break;
        case 'docker_login':
          yaml += `        uses: docker/login-action@v3\n        with:\n          registry: ${step.config.registry || 'docker.io'}\n          username: ${step.config.username || '${{ secrets.DOCKER_USERNAME }}'}\n          password: \${{ secrets.DOCKER_PASSWORD }}\n`;
          break;
        case 'docker_build':
          yaml += `        run: docker build -t ${step.config.dockerImage || 'myapp'}:${step.config.dockerTag || 'latest'} .\n`;
          break;
        case 'docker_push':
          yaml += `        run: docker push ${step.config.dockerImage || 'myapp'}:${step.config.dockerTag || 'latest'}\n`;
          break;
        case 'deploy_ssh':
          yaml += `        uses: appleboy/ssh-action@v1.0.3\n        with:\n          host: \${{ secrets.SSH_HOST || '${step.config.sshHost || 'production.example.com'}' }}\n          username: \${{ secrets.SSH_USER || '${step.config.sshUser || 'deploy'}' }}\n          key: \${{ secrets.SSH_KEY }}\n          port: ${step.config.sshPort || 22}\n          script: |\n            ${(step.config.command || 'docker compose up -d').replace(/\n/g, '\n            ')}\n`;
          break;
        case 'verify_health':
          yaml += `        run: |\n          echo "Verifying health endpoint ${step.config.healthUrl || 'https://api.example.com/health'}"\n          status=$(curl -o /dev/null -s -w "%{http_code}" ${step.config.healthUrl || 'https://api.example.com/health'})\n          if [ "$status" -eq "${step.config.expectedStatus || 200}" ]; then\n            echo "Health check passed with HTTP status $status"\n          else\n            echo "Health check failed with HTTP status $status"\n            exit 1\n          fi\n`;
          break;
        case 'notify_slack':
          yaml += `        uses: slackapi/slack-github-action@v1.26.0\n        with:\n          payload: |\n            {\n              "text": "Deployment workflow completed successfully for ${name || 'noitca'}."\n            }\n        env:\n          SLACK_WEBHOOK_URL: ${step.config.webhookUrl || '${{ secrets.SLACK_WEBHOOK }}'}\n`;
          break;
        default:
          yaml += `        run: |\n          ${(step.config.command || 'echo "Running step"').replace(/\n/g, '\n          ')}\n`;
          break;
      }
    });
  }

  return yaml;
}
